const { Client } = require('pg');

const connectionString = 'postgresql://postgres:Senior%40anandam67@db.vauisjeldrbnqwjvdmya.supabase.co:5432/postgres';

const sql = `
CREATE TABLE IF NOT EXISTS public.custom_types (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    key TEXT UNIQUE NOT NULL,
    icon TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.custom_types ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can view custom_types" ON public.custom_types;
CREATE POLICY "Public can view custom_types" ON public.custom_types FOR SELECT USING (true);

DROP POLICY IF EXISTS "Auth users can manage custom_types" ON public.custom_types;
CREATE POLICY "Auth users can manage custom_types" ON public.custom_types FOR ALL USING (auth.role() = 'authenticated');

-- Insert default types if they don't exist
INSERT INTO public.custom_types (name, key, icon)
VALUES 
  ('Facility Types', 'facility', 'Layers'),
  ('Room Types', 'room', 'Tag'),
  ('Badge', 'badge', 'Award')
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category_group TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can view categories" ON public.categories;
CREATE POLICY "Public can view categories" ON public.categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Auth users can manage categories" ON public.categories;
CREATE POLICY "Auth users can manage categories" ON public.categories FOR ALL USING (auth.role() = 'authenticated');
`;

async function run() {
  const client = new Client({ connectionString });
  try {
    await client.connect();
    await client.query(sql);
    console.log('Database tables successfully applied!');
  } catch (err) {
    console.error('Error applying schema:', err);
  } finally {
    await client.end();
  }
}

run();
