const { Client } = require('pg');

const connectionString = 'postgresql://postgres:Senior%40anandam67@db.vauisjeldrbnqwjvdmya.supabase.co:5432/postgres';

const setupSQL = `
-- Create site_settings table for dynamic hero and video testimonials
CREATE TABLE IF NOT EXISTS public.site_settings (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for site_settings
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- Policy: Anyone can read settings
DROP POLICY IF EXISTS "Public can read settings" ON public.site_settings;
CREATE POLICY "Public can read settings" ON public.site_settings
    FOR SELECT USING (true);

-- Policy: Only authenticated users can manage settings
DROP POLICY IF EXISTS "Auth users can manage settings" ON public.site_settings;
CREATE POLICY "Auth users can manage settings" ON public.site_settings
    FOR ALL USING (auth.role() = 'authenticated');

-- Create communities table
CREATE TABLE IF NOT EXISTS public.communities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    location TEXT NOT NULL,
    type TEXT,
    price TEXT,
    description TEXT,
    rating NUMERIC(2,1) DEFAULT 0,
    reviews INTEGER DEFAULT 0,
    badge TEXT,
    image TEXT,
    about_text TEXT,
    amenities JSONB DEFAULT '[]'::jsonb,
    gallery JSONB DEFAULT '[]'::jsonb,
    quick_facts JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.communities ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can view communities" ON public.communities;
CREATE POLICY "Public can view communities" ON public.communities
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Auth users can manage communities" ON public.communities;
CREATE POLICY "Auth users can manage communities" ON public.communities
    FOR ALL USING (auth.role() = 'authenticated');

-- Create inquiries table
CREATE TABLE IF NOT EXISTS public.inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    community TEXT,
    type TEXT,
    message TEXT,
    status TEXT DEFAULT 'new',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can insert inquiries" ON public.inquiries;
CREATE POLICY "Public can insert inquiries" ON public.inquiries
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Auth users can view inquiries" ON public.inquiries;
CREATE POLICY "Auth users can view inquiries" ON public.inquiries
    FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Auth users can update inquiries" ON public.inquiries;
CREATE POLICY "Auth users can update inquiries" ON public.inquiries
    FOR UPDATE USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Auth users can delete inquiries" ON public.inquiries;
CREATE POLICY "Auth users can delete inquiries" ON public.inquiries
    FOR DELETE USING (auth.role() = 'authenticated');

-- Insert initial site settings if they don't exist
INSERT INTO public.site_settings (key, value)
VALUES 
  ('hero_images', '["/images/hero_indian.png", "https://images.unsplash.com/photo-1516156008625-3a9d6067fab5?auto=format&fit=crop&w=1920&q=80"]'::jsonb),
  ('video_testimonials', '[{"youtubeUrl": "https://www.youtube.com/embed/dvVXX-X47DA", "title": "Vedaanta Brindhavanam Walkthrough", "quote": "Experience a walkthrough of Vedaanta Brindhavanam, where peace meets premium retirement living.", "authorName": "Retire in Peace", "authorDetail": "Property Walkthrough"}]'::jsonb)
ON CONFLICT (key) DO NOTHING;
`;

async function run() {
  const client = new Client({ connectionString });
  try {
    await client.connect();
    console.log('Connected to DB');
    await client.query(setupSQL);
    console.log('Database schema and policies successfully applied!');
  } catch (err) {
    console.error('Error applying schema:', err);
  } finally {
    await client.end();
  }
}

run();
